name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Sync
      env:
        dest: 'deploy@troyearlyvoting.com:/var/www/troyearlyvoting.com/'
      run: |
        echo "${{secrets.DEPLOY_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync \
          --rsh='ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
          --delete \
          --checksum \
          --recursive \
          --verbose \
          --human-readable \
          --exclude deploy_key \
          ./ ${{env.dest}}
